In [1]:
# create a model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
      
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [2]:
# create dataset
features=torch.randn(10, 5)
# create a model
model=Model(features.shape[1])
# call model for forward pass
model(features)



tensor([[0.3109],
        [0.7102],
        [0.5620],
        [0.5219],
        [0.6411],
        [0.4415],
        [0.3740],
        [0.7834],
        [0.6963],
        [0.4483]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show weights and biases
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[ 0.0629,  0.0469, -0.3016,  0.3036, -0.2984]], requires_grad=True)
Parameter containing:
tensor([0.1120], requires_grad=True)


In [6]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Multi-Layer

In [7]:
# create a model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()
      
    
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [8]:
# create dataset
features=torch.randn(10, 5)
# create a model
model=Model(features.shape[1])
# call model for forward pass
model(features)



tensor([[0.4801],
        [0.4169],
        [0.5031],
        [0.4337],
        [0.4295],
        [0.3968],
        [0.3844],
        [0.4196],
        [0.4450],
        [0.4852]], grad_fn=<SigmoidBackward0>)

In [10]:
# show weights and biases
print(model.linear1.weight)
print(model.linear1.bias)
print(model.linear2.weight)
print(model.linear2.bias)


Parameter containing:
tensor([[-0.2205,  0.3637, -0.2255,  0.0369, -0.4242],
        [ 0.0758, -0.4257,  0.0132, -0.2827,  0.4204],
        [ 0.2545, -0.0752,  0.0310, -0.2235,  0.2053]], requires_grad=True)
Parameter containing:
tensor([ 0.2509,  0.1861, -0.2292], requires_grad=True)
Parameter containing:
tensor([[ 0.1272, -0.2797, -0.0802]], requires_grad=True)
Parameter containing:
tensor([-0.2280], requires_grad=True)


In [11]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequential Container

In [12]:
# create a model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )
      
    
    def forward(self, features):
        out = self.network(features)
        return out

In [13]:
# create dataset
features=torch.randn(10, 5)
# create a model
model=Model(features.shape[1])
# call model for forward pass
model(features)



tensor([[0.5171],
        [0.4030],
        [0.4565],
        [0.5171],
        [0.4759],
        [0.4953],
        [0.5123],
        [0.5171],
        [0.4019],
        [0.5171]], grad_fn=<SigmoidBackward0>)

In [15]:
# show weights and biases
print(model.network[0].weight)
print(model.network[0].bias)
print(model.network[2].weight)
print(model.network[2].bias)


Parameter containing:
tensor([[ 0.1576, -0.1335, -0.1692, -0.3913,  0.2055],
        [ 0.0173,  0.1605,  0.3853, -0.1029, -0.3409],
        [ 0.3766,  0.0948,  0.0832,  0.3828,  0.4316]], requires_grad=True)
Parameter containing:
tensor([-0.4272, -0.1679,  0.1527], requires_grad=True)
Parameter containing:
tensor([[ 0.3463, -0.4320, -0.1897]], requires_grad=True)
Parameter containing:
tensor([0.0686], requires_grad=True)


In [16]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00