In [4]:
import torch
print(torch.__version__)

2.4.1+cu121


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"GPU count: {torch.cuda.device_count()}")
    print(f"Current GPU: {torch.cuda.current_device()}")
    print(f"GPU name: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available. Using CPU")

GPU is available!
GPU count: 1
Current GPU: 0
GPU name: NVIDIA GeForce RTX 3090 Ti


# Creating Tensors

In [ ]:
# using empty
a=torch.empty(2, 3) #allocates memory but doesn't initialize values. shows random values from previous memory.
print(a)

tensor([[       nan, 4.2172e-41,        nan],
        [4.2172e-41, 4.4842e-44, 0.0000e+00]])


In [8]:
# check type
print(type(a))

<class 'torch.Tensor'>


In [ ]:
#using zeros
b = torch.zeros(2, 3)
print(b) # all values are zero

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# using ones
c = torch.ones(2, 3)
print(c) # all values are one

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# using rand
d = torch.rand(2, 3)
print(d) # random values between 0 and 1

tensor([[0.4664, 0.5252, 0.9920],
        [0.2819, 0.4846, 0.0766]])


In [12]:
# use of seed
d = torch.rand(2, 3)
print(d)


tensor([[0.1658, 0.0524, 0.2941],
        [0.5639, 0.3308, 0.1152]])


In [13]:
# manual seed
torch.manual_seed(100)
f = torch.rand(2, 3)
print(f)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [ ]:
torch.manual_seed(100)
f = torch.rand(2, 3)
print(f) # same values as before

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [15]:
# using tensor
torch.tensor([[1, 2, 3],[4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways to create tensors

# arange
t = torch.arange(0, 10, 2) # creates a 5 element tensor with values from 0 to 10 having step size 2
print(t)

#using linspace
t = torch.linspace(0, 10, 5) # creates a 5 element tensor with values from 0 to 10 regularly spaced
print(t)

# using eye
t = torch.eye(3) # creates an identity matrix
print(t)

# using full
t = torch.full((2, 3), 5) # creates a 2x3 tensor filled with 5
print(t)

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [19]:
x = torch.tensor([[1, 2, 3],[4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
x.shape

torch.Size([2, 3])

In [21]:
torch.empty_like(x)

tensor([[    129261331656080,          1154085632,                   0],
        [                  0,                   0, 7310593858020254331]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x) # rand generates random numbers between 0 and 1 (floats) while x has integers THATS WHY IT GIVES ERROR

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

# Tensor Data Types

In [25]:
# find the data type of a tensor
x.dtype


torch.int64

In [26]:
# assign data type to a tensor
x = torch.tensor([1, 2, 3], dtype=torch.float32)
x


tensor([1., 2., 3.])

In [28]:
# using to()
x.to(torch.float32)

tensor([1., 2., 3.])

In [29]:
torch.rand_like(x, dtype=torch.float32) # rand generates random numbers between 0 and 1 (floats) while x has integers THATS WHY IT GIVES ERROR. changing dtype to float32 fixes this

tensor([0.2627, 0.0428, 0.2080])

# Mathematical Operations

## Scalar Operations

In [31]:
x=torch.rand(2, 2)
x

tensor([[0.9014, 0.9969],
        [0.7565, 0.2239]])

In [33]:
# Addition
x+2

# Subtraction
x-2

# Multiplication
x*2

# Division
x/2

# Integer Division
x//2

# Power
x**2

# Mod
x%2


tensor([[0.9014, 0.9969],
        [0.7565, 0.2239]])

## Element Wise Operations

In [35]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a)
print(b)


tensor([[0.2472, 0.7909, 0.4235],
        [0.0169, 0.2209, 0.9535]])
tensor([[0.7064, 0.1629, 0.8902],
        [0.5163, 0.0359, 0.6476]])


In [37]:
# Addition
a+b

# Subtraction
a-b

# Multiplication
a*b

# Division
a/b

# Power
a**b

# Mod
a%b

tensor([[0.2472, 0.1394, 0.4235],
        [0.0169, 0.0056, 0.3059]])

In [43]:
c=torch.tensor([1, 2, 3,-4])

In [44]:
# absolute value
c.abs()

tensor([1, 2, 3, 4])

In [45]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [46]:
# negative
-c


tensor([-1, -2, -3,  4])

In [47]:
torch.neg(c)

tensor([-1, -2, -3,  4])

In [48]:
d= torch.tensor([1.9, 2.3, 3.7, 4.1])

In [49]:
# round
d.round()


tensor([2., 2., 4., 4.])

In [50]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [51]:
# CEIL
d.ceil()


tensor([2., 3., 4., 5.])

In [52]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [53]:
# floor
d.floor()


tensor([1., 2., 3., 4.])

In [54]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [55]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [56]:
d.clamp_(min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction Operations

In [65]:
e = torch.randint(size=(2, 3), low=0, high=10,dtype=torch.float32)
print(e)

tensor([[9., 7., 9.],
        [2., 6., 7.]])


In [58]:
# sum
e.sum()


tensor(47)

In [59]:
torch.sum(e)

tensor(47)

In [ ]:
# sum along a specific dimension (along columns)
e.sum(dim=0)

tensor([14, 18, 15])

In [62]:
torch.sum(e, dim=0)

tensor([14, 18, 15])

In [ ]:
e.sum(dim=1) # sum along rows

tensor([25, 22])

In [63]:
torch.sum(e, dim=1)

tensor([25, 22])

In [66]:
# mean
e.mean() #only works with float


tensor(6.6667)

In [67]:
torch.mean(e)

tensor(6.6667)

In [ ]:
# mean along a specific dimension
e.mean(dim=0) # along columns


tensor([5.5000, 6.5000, 8.0000])

In [70]:
torch.mean(e, dim=0)

tensor([5.5000, 6.5000, 8.0000])

In [69]:
e.mean(dim=1) # along rows

tensor([8.3333, 5.0000])

In [71]:
torch.mean(e, dim=1)

tensor([8.3333, 5.0000])

In [72]:
# median
torch.median(e)

tensor(7.)

In [74]:
# min max
torch.min(e)
torch.max(e)

tensor(9.)

In [75]:
# Product
torch.prod(e)

tensor(47628.)

In [76]:
# Standard Deviation
torch.std(e)


tensor(2.5820)

In [77]:
# Variance
torch.var(e)


tensor(6.6667)

In [ ]:
# argmax
torch.argmax(e) # position of max value


tensor(0)

In [ ]:
#argmin
torch.argmin(e) # position of min value


tensor(3)

## Matrix Operations

In [82]:
f = torch.randint(low=0, high=10, size=(2, 3))
g = torch.randint(low=0, high=10, size=(3, 2))
print(f)
print(g)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0],
        [4, 3],
        [8, 8]])


In [83]:
# Matrix Multiplication
torch.mm(f, g)

tensor([[91, 48],
        [74, 43]])

In [84]:
torch.matmul(f, g)

tensor([[91, 48],
        [74, 43]])

In [86]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])
# dot product
torch.dot(vector1, vector2)

tensor(11)

In [87]:
# transpose
torch.transpose(f, 0, 1)

tensor([[7, 6],
        [8, 1],
        [3, 5]])

In [88]:
h = torch.randint(low=0, high=10, size=(3, 3), dtype=torch.float32)
print(h)

tensor([[3., 3., 5.],
        [0., 6., 4.],
        [0., 8., 4.]])


In [ ]:
# determinant
torch.det(h)

tensor(-24.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 3.3333e-01, -1.1667e+00,  7.5000e-01],
        [ 3.6425e-08, -5.0000e-01,  5.0000e-01],
        [-6.1591e-08,  1.0000e+00, -7.5000e-01]])

## Comparison Operators

In [91]:
i = torch.randint(low=0, high=10, size=(2, 3))
j = torch.randint(low=0, high=10, size=(2, 3))
print(i)
print(j)

tensor([[7, 2, 3],
        [8, 5, 6]])
tensor([[2, 9, 5],
        [0, 4, 2]])


In [ ]:
# greater than
i > j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [ ]:
#less than
i < j

tensor([[False,  True,  True],
        [False, False, False]])

In [ ]:
#equal
i == j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# not equal
i != j

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
# greater than or equal
i >= j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [98]:
# less than or equal
i <= j

tensor([[False,  True,  True],
        [False, False, False]])

## Special Functions

In [105]:
k=torch.randint(0, 10, (2, 3),dtype=torch.float32)
k

tensor([[1., 1., 2.],
        [4., 7., 2.]])

In [100]:
# log
torch.log(k)

tensor([[1.9459, 0.0000, 0.0000],
        [1.6094, 1.3863, 1.3863]])

In [101]:
#exp
torch.exp(k)

tensor([[1096.6332,    2.7183,    2.7183],
        [ 148.4132,   54.5981,   54.5981]])

In [102]:
# sqrt
torch.sqrt(k)

tensor([[2.6458, 1.0000, 1.0000],
        [2.2361, 2.0000, 2.0000]])

In [103]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.7311, 0.7311],
        [0.9933, 0.9820, 0.9820]])

In [106]:
# softmax
torch.softmax(k, dim=1)

tensor([[0.2119, 0.2119, 0.5761],
        [0.0471, 0.9465, 0.0064]])

In [107]:
# relu
torch.relu(k)

tensor([[1., 1., 2.],
        [4., 7., 2.]])

## Inplace Operations

In [108]:
m= torch.rand(2, 3)
n= torch.rand(2, 3)
print(m)
print(n)

tensor([[0.6017, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])
tensor([[0.3079, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])


In [109]:
m+n

tensor([[0.9096, 1.0504, 1.3501],
        [1.0769, 0.1227, 1.4047]])

In [110]:
m.add_(n)

tensor([[0.9096, 1.0504, 1.3501],
        [1.0769, 0.1227, 1.4047]])

In [111]:
m

tensor([[0.9096, 1.0504, 1.3501],
        [1.0769, 0.1227, 1.4047]])

In [ ]:
torch.relu(m) # makes a new tensor and consumes more memory

tensor([[0.9096, 1.0504, 1.3501],
        [1.0769, 0.1227, 1.4047]])

In [113]:
m.relu_()

tensor([[0.9096, 1.0504, 1.3501],
        [1.0769, 0.1227, 1.4047]])

In [114]:
m

tensor([[0.9096, 1.0504, 1.3501],
        [1.0769, 0.1227, 1.4047]])

## Copying a tensor

In [115]:
a=torch.rand(2, 3)
a

tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]])

In [ ]:
b=a # not a copy just a new reference to the same tensor

In [117]:
b

tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]])

In [118]:
a[0][0] = 100

In [119]:
a

tensor([[100.0000,   0.7340,   0.8497],
        [  0.9112,   0.4847,   0.9436]])

In [120]:
b

tensor([[100.0000,   0.7340,   0.8497],
        [  0.9112,   0.4847,   0.9436]])

In [121]:
id(a)

129257447664032

In [122]:
id(b)

129257447664032

In [123]:
b=a.clone()

In [124]:
a

tensor([[100.0000,   0.7340,   0.8497],
        [  0.9112,   0.4847,   0.9436]])

In [125]:
b

tensor([[100.0000,   0.7340,   0.8497],
        [  0.9112,   0.4847,   0.9436]])

In [126]:
a[0][0] = 200

In [127]:
a

tensor([[200.0000,   0.7340,   0.8497],
        [  0.9112,   0.4847,   0.9436]])

In [128]:
b

tensor([[100.0000,   0.7340,   0.8497],
        [  0.9112,   0.4847,   0.9436]])

In [129]:
id(a)

129257447664032

In [130]:
id(b)

129257447876384

## Tensor Operations On GPU

In [132]:
torch.cuda.is_available()

True

In [133]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [134]:
# creating a new tensor on GPU
a = torch.rand(2, 3).to(device)
print(a)

tensor([[0.3904, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]], device='cuda:0')


In [136]:
#moving tensors to GPU
a=torch.rand(2, 3)

In [139]:
b=a.to(device)

In [140]:
b+5

tensor([[5.2651, 5.2336, 5.5057],
        [5.5688, 5.0634, 5.8993]], device='cuda:0')

In [141]:
import time

size=10000

matrix_cpu1=torch.rand(size, size)
matrix_cpu2=torch.rand(size, size)

start_time=time.time()
result_cpu=matrix_cpu1 @ matrix_cpu2 #matrix multiplication
end_time=time.time()
cpu_time = end_time-start_time
print(f"CPU time: {cpu_time:.4f} seconds")

matrix_gpu1=matrix_cpu1.to("cuda")
matrix_gpu2=matrix_cpu2.to("cuda")

start_time=time.time()
result_gpu=matrix_gpu1 @ matrix_gpu2 #matrix multiplication
end_time=time.time()
gpu_time = end_time-start_time
print(f"GPU time: {gpu_time:.4f} seconds")
print("\nSpeedup (CPU/GPU):", cpu_time / gpu_time)

CPU time: 2.3847 seconds
GPU time: 0.0127 seconds

Speedup (CPU/GPU): 187.54728868221704


# Reshaping Tensors

In [142]:
a= torch.ones(4,4)
print(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [143]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [145]:
# flatten
a.flatten()


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [147]:
b=torch.rand(2,3,4)
b

tensor([[[0.7262, 0.4660, 0.0610, 0.7108],
         [0.5127, 0.8211, 0.1323, 0.2127],
         [0.9785, 0.3362, 0.7165, 0.1591]],

        [[0.2860, 0.1827, 0.7421, 0.5736],
         [0.1984, 0.7901, 0.9421, 0.7998],
         [0.1199, 0.6392, 0.3352, 0.9893]]])

In [148]:
# permute
b.permute(2,1,0)


tensor([[[0.7262, 0.2860],
         [0.5127, 0.1984],
         [0.9785, 0.1199]],

        [[0.4660, 0.1827],
         [0.8211, 0.7901],
         [0.3362, 0.6392]],

        [[0.0610, 0.7421],
         [0.1323, 0.9421],
         [0.7165, 0.3352]],

        [[0.7108, 0.5736],
         [0.2127, 0.7998],
         [0.1591, 0.9893]]])

In [150]:
# unsqueeze
c=torch.rand(226,226,3)
print(c.shape)
print(c.unsqueeze(2).shape)

torch.Size([226, 226, 3])
torch.Size([226, 226, 1, 3])


In [164]:
# squeeze
d=torch.rand(1,20)
# print(c.shape)
print(d.squeeze(0).shape)

torch.Size([20])


# Numpy and PyTorch

In [1]:
import numpy as np

In [5]:
a=torch.tensor([1,2,3])

In [6]:
b=a.numpy()

In [7]:
b

array([1, 2, 3])

In [8]:
type(b)

numpy.ndarray

In [9]:
c=np.array([1,2,3])

In [10]:
torch.from_numpy(c)

tensor([1, 2, 3])