In [15]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [16]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


# Train-Test Split

In [17]:
# Train-Test Split

df = df.drop(columns=["Unnamed: 32"], errors="ignore")

x = df.drop(columns=["id", "diagnosis"])
y = df["diagnosis"].map({"M": 1, "B": 0}) # label encoding: Malignant = 1, Benign = 0

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y
)

# Scaling

In [18]:
scaler = StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [19]:
x_train

array([[ 0.51855873,  0.89182579,  0.4246317 , ..., -0.23574392,
         0.05456632,  0.02183673],
       [-0.51636409, -1.63971029, -0.54134872, ..., -0.32320788,
        -0.13757624, -0.90440164],
       [-0.36811839,  0.45551496, -0.38824993, ..., -0.89082504,
        -0.675893  , -0.14401559],
       ...,
       [-0.32616206,  1.33280304, -0.38905998, ..., -0.84289958,
        -0.96490082, -1.16888375],
       [ 0.00948859,  0.25952507,  0.00786279, ...,  0.27571059,
        -0.60284707, -0.30545988],
       [ 0.80945595,  0.36918608,  0.79320285, ...,  1.00657384,
        -0.46151907, -0.44817001]])

In [20]:
y_train

10     1
170    0
407    0
430    1
27     1
      ..
37     0
415    0
458    0
476    0
335    1
Name: diagnosis, Length: 455, dtype: int64

# Lable Encoding

In [21]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)


In [22]:
y_train

array([1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,

# Numpy arrays To Pytorch tensors

In [23]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [24]:
x_train_tensor

tensor([[ 0.5186,  0.8918,  0.4246,  ..., -0.2357,  0.0546,  0.0218],
        [-0.5164, -1.6397, -0.5413,  ..., -0.3232, -0.1376, -0.9044],
        [-0.3681,  0.4555, -0.3882,  ..., -0.8908, -0.6759, -0.1440],
        ...,
        [-0.3262,  1.3328, -0.3891,  ..., -0.8429, -0.9649, -1.1689],
        [ 0.0095,  0.2595,  0.0079,  ...,  0.2757, -0.6028, -0.3055],
        [ 0.8095,  0.3692,  0.7932,  ...,  1.0066, -0.4615, -0.4482]],
       dtype=torch.float64)

In [26]:
x_train_tensor.shape

torch.Size([455, 30])

In [25]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [38]:



class MySimpleNN():

    def __init__(self, x):
        self.weights=torch.rand(x.shape[1], 1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

    def forward(self,x):
        z = torch.matmul(x,self.weights)+self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self,y_pred,y):
        # clamp prediction to avoid log(0)
        epsilon = 1e-15
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss
        


# Important Parameters

In [40]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [32]:
# Create Model
model = MySimpleNN(x_train_tensor)
print("Weights:")
print(model.weights)
print("Bias:")
print(model.bias)


Weights:
tensor([[0.1608],
        [0.3871],
        [0.2938],
        [0.5858],
        [0.8130],
        [0.3129],
        [0.8850],
        [0.9953],
        [0.9457],
        [0.7851],
        [0.6405],
        [0.7127],
        [0.1408],
        [0.4185],
        [0.8420],
        [0.7083],
        [0.8742],
        [0.0838],
        [0.4384],
        [0.6362],
        [0.7712],
        [0.7360],
        [0.9892],
        [0.1432],
        [0.9637],
        [0.0217],
        [0.5163],
        [0.1128],
        [0.0238],
        [0.6070]], dtype=torch.float64, requires_grad=True)
Bias:
tensor([0.], dtype=torch.float64, requires_grad=True)


In [41]:
# Create Model
model = MySimpleNN(x_train_tensor)
# Define loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model.forward(x_train_tensor)
    # print(y_pred)

    # Calculate Loss
    loss = model.loss_function(y_pred, y_train_tensor)
    
    
    # Backward Pass
    loss.backward()
    
    # Update Parameters
    with torch.no_grad():
        model.weights-=learning_rate*model.weights.grad
        model.bias-=learning_rate*model.bias.grad
    
    # Zero Gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # Print loss in each epoch
    
    print(f"Epoch {epoch+1}: Loss = {loss.item()}")


Epoch 1: Loss = 3.688601212722641
Epoch 2: Loss = 3.4843538243048915
Epoch 3: Loss = 3.2797445297314494
Epoch 4: Loss = 3.073638953814965
Epoch 5: Loss = 2.8701734990326235
Epoch 6: Loss = 2.6699157977482453
Epoch 7: Loss = 2.473584999209801
Epoch 8: Loss = 2.2820667187886277
Epoch 9: Loss = 2.0964365837724155
Epoch 10: Loss = 1.9179738736656577
Epoch 11: Loss = 1.7481577412415872
Epoch 12: Loss = 1.5886410394464248
Epoch 13: Loss = 1.4411991100794772
Epoch 14: Loss = 1.3076447587818458
Epoch 15: Loss = 1.1896786847772425
Epoch 16: Loss = 1.0886241944967598
Epoch 17: Loss = 1.0050356302605894
Epoch 18: Loss = 0.9383224363192433
Epoch 19: Loss = 0.8866780607273488
Epoch 20: Loss = 0.8474787506577429
Epoch 21: Loss = 0.8179261202627215
Epoch 22: Loss = 0.7955401782523369
Epoch 23: Loss = 0.7783568568853161
Epoch 24: Loss = 0.7649215505973919
Epoch 25: Loss = 0.7541991558168306


In [ ]:
model.weights # trained weights

tensor([[ 0.1190],
        [ 0.1201],
        [ 0.3978],
        [-0.0761],
        [ 0.3926],
        [-0.0829],
        [-0.1048],
        [-0.4230],
        [ 0.1825],
        [-0.0684],
        [-0.0462],
        [ 0.0636],
        [ 0.3871],
        [ 0.4083],
        [-0.1726],
        [ 0.0826],
        [-0.2510],
        [ 0.0010],
        [ 0.0185],
        [ 0.5316],
        [-0.3406],
        [-0.0691],
        [-0.1851],
        [-0.0245],
        [ 0.1492],
        [-0.5071],
        [ 0.1519],
        [-0.1487],
        [ 0.1049],
        [ 0.2659]], dtype=torch.float64, requires_grad=True)

In [43]:
model.bias # trained bias

tensor([-0.1559], dtype=torch.float64, requires_grad=True)

# Evaluation

In [46]:
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred=(y_pred>0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5484764575958252
