In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


# Train-Test Split

In [4]:
# Train-Test Split

df = df.drop(columns=["Unnamed: 32"], errors="ignore")

x = df.drop(columns=["id", "diagnosis"])
y = df["diagnosis"].map({"M": 1, "B": 0}) # label encoding: Malignant = 1, Benign = 0

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y
)

# Scaling

In [5]:
scaler = StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [6]:
x_train

array([[ 0.51855873,  0.89182579,  0.4246317 , ..., -0.23574392,
         0.05456632,  0.02183673],
       [-0.51636409, -1.63971029, -0.54134872, ..., -0.32320788,
        -0.13757624, -0.90440164],
       [-0.36811839,  0.45551496, -0.38824993, ..., -0.89082504,
        -0.675893  , -0.14401559],
       ...,
       [-0.32616206,  1.33280304, -0.38905998, ..., -0.84289958,
        -0.96490082, -1.16888375],
       [ 0.00948859,  0.25952507,  0.00786279, ...,  0.27571059,
        -0.60284707, -0.30545988],
       [ 0.80945595,  0.36918608,  0.79320285, ...,  1.00657384,
        -0.46151907, -0.44817001]])

In [7]:
y_train

10     1
170    0
407    0
430    1
27     1
      ..
37     0
415    0
458    0
476    0
335    1
Name: diagnosis, Length: 455, dtype: int64

# Lable Encoding

In [8]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)


In [9]:
y_train

array([1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,

# Numpy arrays To Pytorch tensors

In [10]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [11]:
x_train_tensor

tensor([[ 0.5186,  0.8918,  0.4246,  ..., -0.2357,  0.0546,  0.0218],
        [-0.5164, -1.6397, -0.5413,  ..., -0.3232, -0.1376, -0.9044],
        [-0.3681,  0.4555, -0.3882,  ..., -0.8908, -0.6759, -0.1440],
        ...,
        [-0.3262,  1.3328, -0.3891,  ..., -0.8429, -0.9649, -1.1689],
        [ 0.0095,  0.2595,  0.0079,  ...,  0.2757, -0.6028, -0.3055],
        [ 0.8095,  0.3692,  0.7932,  ...,  1.0066, -0.4615, -0.4482]],
       dtype=torch.float64)

In [12]:
x_train_tensor.shape

torch.Size([455, 30])

In [13]:
y_train_tensor.shape

torch.Size([455])

In [15]:
from torch.utils.data import Dataset, DataLoader

In [16]:
class CustomDataset(Dataset):
    def __init__(self, features,labels):
        self.features = features
        self.labels = labels
    
    def __len__(self):
        return len(self.features)
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [17]:
train_dataset= CustomDataset(x_train_tensor, y_train_tensor)
test_dataset= CustomDataset(x_test_tensor, y_test_tensor)

In [18]:
train_loader= DataLoader(train_dataset, batch_size=2, shuffle=True)
test_loader= DataLoader(test_dataset, batch_size=2, shuffle=True)

# Defining the model

In [19]:
import torch
import torch.nn as nn


class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

    # def loss_function(self,y_pred,y):
    #     # clamp prediction to avoid log(0)
    #     epsilon = 1e-15
    #     y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    #     loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    #     return loss
        


In [20]:
# Define Loss Function
loss_function = nn.BCELoss()

# Important Parameters

In [22]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [22]:
# Create Model
model = MySimpleNN(x_train_tensor.shape[1])
print("Weights:")
print(model.linear.weight)
print("Bias:")
print(model.linear.bias)


Weights:
Parameter containing:
tensor([[-0.1434,  0.1117,  0.1364, -0.1590, -0.1122,  0.0362,  0.0619, -0.0585,
         -0.0292,  0.1073, -0.1610, -0.1466,  0.1122, -0.1313, -0.1326,  0.1775,
          0.0692, -0.0898, -0.0894, -0.0876, -0.1822, -0.0934,  0.0909, -0.1819,
          0.0238, -0.0500,  0.0749, -0.0823, -0.1707, -0.1532]],
       requires_grad=True)
Bias:
Parameter containing:
tensor([0.0130], requires_grad=True)


In [23]:
x_train_tensor = x_train_tensor.float()
y_train_tensor = y_train_tensor.float()
# Create Model
model = MySimpleNN(x_train_tensor.shape[1])
# Define Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Define loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model(x_train_tensor)
    # print(y_pred)

    # Calculate Loss
    loss = loss_function(y_pred, y_train_tensor.reshape(-1, 1))
    
    # Zero Gradients
    optimizer.zero_grad()
    
    # Backward Pass
    loss.backward()
    
    # Update Parameters
    optimizer.step()
    
    # Print loss in each epoch
    
    print(f"Epoch {epoch+1}: Loss = {loss.item()}")


Epoch 1: Loss = 0.8690525889396667
Epoch 2: Loss = 0.6448226571083069
Epoch 3: Loss = 0.5246652364730835
Epoch 4: Loss = 0.4516741931438446
Epoch 5: Loss = 0.4020111858844757
Epoch 6: Loss = 0.36560148000717163
Epoch 7: Loss = 0.33750852942466736
Epoch 8: Loss = 0.31502285599708557
Epoch 9: Loss = 0.29652610421180725
Epoch 10: Loss = 0.2809864282608032
Epoch 11: Loss = 0.2677117586135864
Epoch 12: Loss = 0.25621771812438965
Epoch 13: Loss = 0.24615363776683807
Epoch 14: Loss = 0.23725834488868713
Epoch 15: Loss = 0.2293323129415512
Epoch 16: Loss = 0.22222015261650085
Epoch 17: Loss = 0.21579861640930176
Epoch 18: Loss = 0.2099684774875641
Epoch 19: Loss = 0.20464888215065002
Epoch 20: Loss = 0.1997731477022171
Epoch 21: Loss = 0.19528576731681824
Epoch 22: Loss = 0.19114015996456146
Epoch 23: Loss = 0.18729694187641144
Epoch 24: Loss = 0.1837225705385208
Epoch 25: Loss = 0.18038830161094666


In [ ]:
model.weights # trained weights

tensor([[ 0.1190],
        [ 0.1201],
        [ 0.3978],
        [-0.0761],
        [ 0.3926],
        [-0.0829],
        [-0.1048],
        [-0.4230],
        [ 0.1825],
        [-0.0684],
        [-0.0462],
        [ 0.0636],
        [ 0.3871],
        [ 0.4083],
        [-0.1726],
        [ 0.0826],
        [-0.2510],
        [ 0.0010],
        [ 0.0185],
        [ 0.5316],
        [-0.3406],
        [-0.0691],
        [-0.1851],
        [-0.0245],
        [ 0.1492],
        [-0.5071],
        [ 0.1519],
        [-0.1487],
        [ 0.1049],
        [ 0.2659]], dtype=torch.float64, requires_grad=True)

In [18]:
model.linear.bias # trained bias

Parameter containing:
tensor([-0.0134], requires_grad=True)

# Evaluation

In [25]:
x_test_tensor = x_test_tensor.float()
y_test_tensor = y_test_tensor.float()

In [26]:
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred=(y_pred>0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5392428636550903
